services:
  postgres:
    image: postgres:18
    container_name: patient-service-db
    environment:
      POSTGRES_DB: patientdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
#    ports:
#      - "5000:5432"
    volumes:
      - C:\Users\hp\myVolumes\patient-service-db:/var/lib/postgresql

  kafka:
    image: apache/kafka:4.1.1
    container_name: kafka
    ports:
      - "9094:9094" # for external communication
#      - "9092:9092" # for internal communication inside same network (avoid expose to it)
    environment:
      # ---- KRaft mode ----
      KAFKA_NODE_ID: 0
      KAFKA_PROCESS_ROLES: controller,broker

      # ---- Listeners ----
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT

      # ---- Controller ----
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 0@kafka:9093

      # ---- Required for single node ----
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

      # ---- Optional ----
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"


  billing-service:
    image: billing-service:latest
    container_name: billing-service
    depends_on:
      - postgres
#    ports:
#      - "4002:4002"
#      - "9001:9001"

  analytics-service:
    image: analytics-service:latest
    container_name: analytics-service
    depends_on:
      - kafka
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092

  patient-service:
    image: patient-service:latest
    container_name: patient-service
    depends_on:
      - billing-service
      - postgres
    environment:
      BILLING_SERVICE_ADDRESS: billing-service
      BILLING_SERVICE_GRPC_PORT: 9001
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/patientdb
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: secret
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_SQL_INIT_MODE: always
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092

#    ports:
#      - "4001:4001" # only needed if you want to access service from host

  api-gateway:
    image: api-gateway:latest
    container_name: api-gateway
    depends_on:
      - patient-service
    ports:
      - "4000:4000"
    # docker compose -f docker-compose.yml up -d